# Generated by Django 2.2.10 on 2021-11-14 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_text',
            field=models.CharField(default=1, max_length=255, verbose_name='Ответ текстом'),
            preserve_default=False,
        ),
    ]
